### PR TITLE
Add new filter to change the port file path

### PR DESCRIPTION
**Pull request by igmoweb**
The code assumes that we're always working on a theme but we could be using a plugin. This is an actual case for The Sun.

### CODE REVIEW

**Comment by rmccue** [comment]
Could we make the root directory a parameter to `enqueue_assets()` instead? e.g. `enqueue_assets( __DIR__, 'theme-name', [ 'maybe', 'deps' ] )`

**Comment by rmccue** [comment]
Actually, better idea, let's redesign the interface to this:

```php
<?php
/**
 * @param string $directory Root directory containing `src` directory.
 * @param array $opts {
 *     @type string $handle Style/script handle. (Default is last part of directory name.)
 *     @type array  $scripts Script dependencies.
 *     @type array  $styles  Style dependencies.
 * }
 */
function enqueue_assets( $directory, $opts = [] );
```

**Comment by igmoweb** [comment]
@rmccue `enqueue_assets` is not enqueuing any style. Do we want to do that? When Webpack is up, we don't need to enqueue styles at all, they are inserted inline

**Comment by igmoweb** [comment]
@rmccue I pushed a few changes:
1. I added the interface you said but also an extra `base_url` param for production builds.
2. The JS and CSS filenames are now read from `assets-manifest.json` (for production)

**Comment by igmoweb** [comment]
@rmccue We've been testing this branch for a few weeks and it's working fine for both, dev and build environments. Do we want to do anything else here?

**Comment by kadamwhite** [comment]
@igmoweb I incorporated much of this PR into #6 which just landed, could you test out with the latest and let me know if that one supersedes this?

**Comment by igmoweb** [comment]
Excellent @kadamwhite . Closing here.

**Pull request closed without merging**
