### PR TITLE
Use localhost as hostname for assets.

### LINKED ISSUE #14: Scripts are loaded from 0.0.0.0 instead of 127.0.0.1
The asset manifest is output with URLs like `http://0.0.0.0:3001/main.js`. This needs to translate the IP to the actual IP rather the IP binding it currently has.

### PR DESCRIPTION
**Pull request by tfrommen**
Fix #14.

----

Use `localhost` over `0.0.0.0`.

See also:
* https://github.com/middleman/middleman/issues/1011
* https://github.com/senecajs/seneca-transport/issues/37
* ...

### CODE REVIEW

**Comment by joehoyle** [comment]
Ran into this also!

**Comment by tfrommen** [comment]
Update: there was some issues reported that just `localhost` might not work anymore on Docker etc. I asked @mattheu to test this, and it seems to work just fine.

**Comment by joehoyle** [comment]
FWIW you can override this at runtime, which I've been doing as a workaround (0.0.0.0 doesn't route to the machine, as far as I understand 0.0.0.0 is not actually a valid IP, it's a listener directive. 

```
HOST='localhost' npx react-wp-scripts start
```

**Comment by mattheu** [comment]
Yeah this seemed to work OK for me after this change.

**Comment by tfrommen** [comment]
Is this what you were talking about, @rmccue? Still working, @mattheu, @joehoyle?

**Pull request merged**
